### ISSUE TITLE
API parameters are sometimes kebab-case and sometimes camelCase

### ISSUE THREAD

**Issue by rripken** [USACE/cwms-data-api#136]
Several of the api parameters are camelCase:
pageSize, unitSystem, categoryLike, groupLike, includeValues, dataSet
Others are kebab-case:
id-mask, pool-id, group-id, category-id

We should consistently name the parameters.

The Swagger annotation @OpenApiParam that builds the Swagger interface has a deprecated field.  We could mark the incorrectly spelled parameter as deprecated and the add a correctly named parameter.  In the Controller implementation we could check for both spellings until the deprecated parameter is completely removed so that clients have a chance to roll over to the new parameter.  Not sure how to communicate to clients that they need to change.  Maybe once the deprecated parameter is removed we flip a switch and instead of the old parameter silently working anything using the old parameter is given an error page that explicitly calls out the no-longer supported parameter and what it should be replaced with?

**Comment by MikeNeilson** [comment]
That plan makes sense to me. However, should we go to camel or kebab case. I like the visual look of kebab, but it is definitely easier in JavaScript to have camel; you can use normal accessor methods.

**Comment by MikeNeilson** [comment]
I'm feeling kebab myself. what do you think?
@DanielTOsborne ?
@adamscarberry ?

**Comment by DanielTOsborne** [comment]
> 

I don't have full context for which parts of the API are problematic, but my preference is kebab-case for REST parameters, which would match the casing of the data returned.
For Java classes though, map those to camelCase.

Example:
REST API parameter (and in the result): page-size
Maps to Java property: pageSize

**Comment by adamscarberry** [comment]
My opinion... it would be between **snake_case** and **spinal-case** (kebab).  camelCase in the url in not terrible, but if I can eliminate the possible mistake by a user because they forgot to uppercase (on Linux based servers), that's one less potential support issue.  Plus I don't have to think about it myself if everything is lower case.

Not a huge factor, but with snake_case I can name my variables the same in javascript/python/etc without issue.  I can't use '-' in most language variables (it will think I'm trying to subtract two new variables).

Resource of interest: https://blog.restcase.com/5-basic-rest-api-design-guidelines/

**Comment by MikeNeilson** [comment]
That's a good point had honestly forget about snake_case, which is silly considering the amount of c++ programming I've been doing within the last 2-3 weeks.

But the interopability is important, it would simplify downstream uses, and javascript is very likely to be an important one.

**Comment by rripken** [comment]
kebab seems pretty common and gets my vote.

**Comment by MikeNeilson** [comment]
Okay, the vote is 2 kabab and (2 kabab fine, snake has useful properties.) Since this is software and nothing is sent in stone
Kabab passes.

If it turns out that was a wrong decision, well we can just transition again. Or figure out a way to support both. That jackson json has almost as many ways to be taken control of as the c++ standard template library, so likely not that hard if push comes to shove.
