### ISSUE TITLE
Migrate metrics to prometheus or openmetrics library.

### ISSUE THREAD

**Issue by MikeNeilson** [USACE/cwms-data-api#148]
I'd like to see whom data is getting queried for. Right now it's just how much, not split amongst the districts.

**Comment by rma-rripken** [comment]
Will this issue remove the codahale dependency or is it supposed to figure out a way to add the office_id (and other parameters) to the data collected?

I think codahale would handle what you are asking for by finding/creating an additional office-specific meter/timer.  So instead of starting a single meter it would start the global meter without the office and then also start another meter that was specific to the office.    In many Controllers I've switched from declaring the meters/timers up front to having them created on-demand in a markAndTime method.  If you wanted another set of meters that were office specific (or really depended on any set of attributes) an additional markAndTime signature could be created that took in a map of additional attributes and could build one meter without all the attributes and another that included the attributes in the path.   

Or perhaps open-telemetry could be used?

It has a metrics api somewhat similar to codahale:
https://github.com/open-telemetry/opentelemetry-java-docs/blob/main/metrics

In open-telemetry there seems to be the ability to add attributes to things.  See:

https://opentelemetry.io/docs/instrumentation/java/manual/#span-attributes

I'm not sure if that attribute ability applies to the metrics portion of the library or just the tracing part.  That would need someone to do some exploration to figure out.

**Comment by MikeNeilson** [comment]
yes, that said if we can figure it out within codehale I'm not opposed to keeping it, but unit the next version they way prometheus works wasn't well supported.

**Comment by MikeNeilson** [comment]
though I believe open-telemetry implements the open metrics concept so were on the same page there.

Altertively I've just starting working more with JMX MBeans and the JMX system includes an exporter. So custom beans may actually work better for us. hard to say.

**Comment by MikeNeilson** [comment]
Superseded by #352
