### ISSUE TITLE
Vertical Datum not always being returned.  Should it?

### ISSUE THREAD

**Issue by rma-rripken** [USACE/cwms-data-api#192]
When should VD be included?

It looks like TimeSeriesDaoImpl.getTimeseries only includes the Vertical Datum (VD) if the param part is ELEV.   Its only ELEV because of:
 ```
DSL.choose(valid.field("parm_part",String.class))
							.when(
								"ELEV",
								CWMS_LOC_PACKAGE.call_GET_VERTICAL_DATUM_INFO_F__2(
									valid.field("loc_part",String.class),
									valid.field("units",String.class),
									valid.field("office_id",String.class)))
							.otherwise("")
```

Is ELEV the only parameter that should include VD?  Seems like STAGE might make sense as well.

Kevin expected VD when querying for precip ts like: PleasantHill.Precip.Total.15Minutes.15Minutes.USGS.   I believe he was expecting it because Right or Wrong CWMSVue was showing VD for every TS at PleasantHill.

Curiously, even though the JOOQ has that otherwise("") clause - when I debug the value of the VERTICAL_DATUM query field is coming back as null and not "".  The VD parsing code handles null and empty the same way but I was a bit disappointed that it wasn't working the way I expected.

**Comment by MikeNeilson** [comment]
That's a good question. I honestly have no idea. The vertical datum makes the most sense for elevation as that is elevation above a datum.

Stage also makes since it's just above a local datum to keep the numbers reasonable but I can see value in transforming to real elevation.

Precip on the other hand. Makes sense in the catalog for the elevation of the site itself, but the "real" physical bottom of the rain gauge or level for surface doesn't matter. You're just get the relative volume of water that dropped.

If we started allowing that in for other than Elev/Stage I'd be concerned people would be trying to apply that instantaneous value as something it isn't.

**Comment by perrymanmd** [comment]
The intent was for it to pertain to ELEV only as that is the only parameter affected by it. It is true that some people use STAGE for ELEV values because, well I guess they always have done so. However there is also lots of usage of STAGE that is *not* ELEV. I think it's cleaner to tell people to not use STAGE for ELEV than to sometimes conflate the two and sometimes not. The DB *does* allow specifying a datum offset from the native ELEV datum to STAGE, but I don't think its ever been used.

**Comment by adamkorynta** [comment]
CWMSVue displays location metadata for every row of time series. It isn’t used as the basis for adding vertical datum offsets to the time series itself.

**Comment by perrymanmd** [comment]
In that case I would call `Cwms_Loc.Get_Vertical_Datum_Info_F(Location_Code, Unit)` for the location to retrieve the info whenever you retrieve the location and then you have it regardless of what time series the location has.

**Comment by rma-rripken** [comment]
Just so I understand the suggestion correctly, should the Radar timeseries end-point be doing that call and returning VD with each timeseries or are you suggesting that CwmsVue should be doing that call and joining timeseries and location metadata to get VD to their table?   If VD doesn't really make sense for a timeseries my preference would be to have Radar not return it but I don't have a firm grasp on how much work it would be to have CwmsVue do it.

**Comment by rma-rripken** [comment]
It sounds like CwmsVue is already doing the right thing.  I think that Radar probably doesn't have to change.
