### ISSUE TITLE
Add timeseries rename and update endpoints

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#268]
The rename feature is used to change the time series identifier and the update feature is used set active flags and change the interval offset. (cwms_ts.rename_ts and cwms_ts_update_ts_id procedures respectively)

**Comment by rma-rripken** [comment]
There is already a timeseries update end-point but I believe it serves a different purpose but I'm not sure anyone has been able to use it b/c of authorization.  Could it be reworked?  

We should consider using Json-Patch  ( http://jsonpatch.com/ ).   Instead of sending the objects as we want them to be, we send a series of explicit transformations we want to have happen in the patch.

Even if the existing end-point is being used and can't be reworked we could add a new mime-type for json-patch.

**Comment by MikeNeilson** [comment]
That honestly looks like it could be confusing to the end users. Sure, Adam writing the hec-cwms-data-access code wouldn't care. But we kinda want this to be easy for anyone.

What about something like `.../timeseries/{original-id}/rename-to/{new-id}`?

Those rest endpoints are supposed to be a little sentence like.

**Comment by rma-rripken** [comment]
Summary of work to date:   I'm in the process of creating a new TimeseriesIdentifier end-point.   This will let rename/update/delete happen without having to involve the existing TimeSeries objects.  
I did some experiments with serializing the mil.army.usace.hec.metadata.* classes directly into the CDA output and I got it to work but I believe it would make the java client rely on hec-nucleus-metadata so I stopped that line of work and did the object->dto mapping that we've had to do other places.
