### ISSUE TITLE
What happens when a client closes their connection after making a request but before getting the response? 

### ISSUE THREAD

**Issue by rma-rripken** [USACE/cwms-data-api#464]
Do we know or can we investigate what happens when a client closes their connection after making a slow request but before getting a response?   
Can Javalin detect that via exception or something else?
If detected can CDA stop or interrupt a corresponding jOOQ query?

I'm thinking of the scenario where a catalog call is taking 60s to complete.  The user gets impatient and refreshes and issues another 60s call.   Is there anything we can do to avoid DOS?

**Comment by MikeNeilson** [comment]
I suspect that's more up to the servlet container engine and how it handles terminated connections.
*IF* the client actually properly terminates the session; e.g. doesn't just kill the connection but actually sends the shutdown sequence, Tomcat/Jetty/etc could then decide to terminate the work on the thread running that task.

Otherwise the server can't know until it attempts to actually send the data back.
