### ISSUE TITLE
Add id queryParameter to Clob end-point 

### ISSUE THREAD

**Issue by rma-rripken** [USACE/cwms-data-api#520]
If provided this overrides the id pathParameter.
Needed to work around clobId that contain slashes

**Comment by MikeNeilson** [comment]
This *may* also be a good time to start down the path of a "UUID/integer primary key" key like thing to be able to pass to the endpoint path parameter.

e.g. since it have intentionally *NOT* been returning the database code fields we could start (but not the code or using code) by encoding the office and name of the element similar to the paging.

e.g. office / name -> base64

... maybe not slash though. 

That said the queryParameter id would still be desired so definitely focus on that. If a simplified path parameter can be done that would set the path forward for the other end points.
