### ISSUE TITLE
TimeSeries v2 endpoints date format does not quite match the documentation

### ISSUE THREAD

**Issue by rripken** [USACE/cwms-data-api#74]
The documentation for TimeSeries start/end claim ISO 8601 extended with an example.  
But the example is subtly different from what the TimeSeries v2 Dao is expecting.
The documentation gives the example of 2021-06-10T13:00:00-0700[PST8PDT] 
But I believe the v2 Dao is expecting something that will parse with DateTimeFormatter.ISO_DATE_TIME.   I believe the above example would need to be changed so that the -0700 part includes a colon like : -07:00.
Perhaps we need to be more flexible in date parsing and try parsing with a couple of different formats?

It seems a little weird that the API accepts dates in one format but then the results returned use a different format (the ZONED_DATE_TIME_FORMAT inside TimeSeries).

Should the legacy xml/json end-points be adjusted to use a common date format with the newer end-points and then those input values converted to whatever format the pl/sql is expecting?

**Comment by MikeNeilson** [comment]
There is an additional issue where by default a lot of web servers strip the [ and ] characters from URLs. Fortunately there is no specific STIG related requirement for that, but it is a concern.

As for adjusting the legacy formats. Unfortunately no, instead we should plan for their retirement. We must maintain backwards compatibility for a while yet. Once we can provide more training and get people off the hold mechanisms we can remove them.

**Comment by rma-rripken** [comment]
This is related to  #147

**Comment by rma-rripken** [comment]
The with or without colon issue could be solved by the suggestions here: 
https://stackoverflow.com/questions/66812557/how-to-parse-a-date-with-timezone-with-and-without-colon/66812678#66812678

**Comment by rma-rripken** [comment]
I think my suggestion about working with the legacy pl/sql was misunderstood but I think we're on the same page.   I'm not suggesting that Radar modify the legacy pl/sql calls.   I'm suggesting that Radar always parse the start/end date strings with a standard format into a ZonedDateTime and when Radar is required to forward calls into pl/sql b/c of the format query param or similar that Radar then internally formats the ZonedDateTime into the appropriate String format for the pl/sql call that is about to be made.    It would be too difficult to try and document which formats are expected by which combinations of arguments.

**Comment by MikeNeilson** [comment]
Oh yes, that I completely agree with. Sorry.

**Comment by MikeNeilson** [comment]
> The with or without colon issue could be solved by the suggestions here: https://stackoverflow.com/questions/66812557/how-to-parse-a-date-with-timezone-with-and-without-colon/66812678#66812678

Okay, I remember looking that up also. Did it not get implemented anywhere already?

**Comment by rma-rripken** [comment]
I've got the without colon format parsing but I haven't submitted it yet but as I'm looking at this code and reading the swagger documentation there is a disagreement about what happens with start/end times and the timezone.

The end parameter is documented like this:
`Specifies the end of the time window for data to be included in the response. If this field is not specified, any required time window ends at the current time. The format for this field is ISO 8601 extended, with optional timezone, i.e., 'YYYY-MM-dd'T'hh:mm:ss[Z'['VV']']', e.g., '2021-06-10T13:00:00-0700[PST8PDT]'.`

The timezone parameter is documented like this:
`Specifies the time zone of the values of the begin and end fields (unless otherwise specified), as well as the time zone of any times in the response. If this field is not specified, the default time zone of UTC shall be used. Ignored if begin was specified with offset and timezone.`

When I read those two statements my conclusion is that if I supply begin and end in a format that includes timezone information than I don't really need to worry about what is passed to the timezone parameter.  The timezone description includes words like "unless otherwise specified" and "ignored". 

That doesn't seem to be how DateUtils.parseUserDate is coded.   At the moment the parseUserDate method seems to parse whatever string the user provided and throw away the parsed timezone information and use whatever timezone was in the timezone arg which isn't how I'd understand "unless otherwise specified" to work.  

How should the start/end/timezone args work?  

DateUtils.parseUserPeriod and DateUtils.parseUserDuration are also creeping me out b/c the methods take a timezone and then do nothing with it.

When this issue is closed it would be great if the datetime parsing was solid, well tested and could be reused across all the controllers that need a ZonedDateTime and all the datetime parameter documentation matched what was being done.

**Comment by rma-rripken** [comment]
I think maybe the call In DateUtils to ZoneDateTime.withZoneSameLocal was supposed to be ZoneDateTime.withZoneSameInstant.  
withZoneSameLocal keeps the local time the same (e.g 7pm) and changes the timezone.  Which completely changes the instant if the timezones were different one of the times will now happen before the other.
withZoneSameInstant translates the old time into a new one but both refer to the same instant.  Even if the timezones were different both ZoneDateTime happen at the same time.

**Comment by MikeNeilson** [comment]
well, that would certainly break things.

**Comment by rma-rripken** [comment]
> well, that would certainly break things.

I know.  Which made me revisit #296 a couple times.  Please double/triple check that DateUtils.parseUserDate is doing what you think it should and that you agree with the values for the hours in the expected values of the cases.   Note, I ended up taking out the call to withZoneSameInstant.  If the text included a zone of some form we should just use it - why convert the times to use the backup timezone?

**Comment by DanielTOsborne** [comment]
> The timezone parameter is documented like this: `Specifies the time zone of the values of the begin and end fields (unless otherwise specified), as well as the time zone of any times in the response. If this field is not specified, the default time zone of UTC shall be used. Ignored if begin was specified with offset and timezone.`
> 
> When I read those two statements my conclusion is that if I supply begin and end in a format that includes timezone information than I don't really need to worry about what is passed to the timezone parameter. The timezone description includes words like "unless otherwise specified" and "ignored".
> 
> That doesn't seem to be how DateUtils.parseUserDate is coded. At the moment the parseUserDate method seems to parse whatever string the user provided and throw away the parsed timezone information and use whatever timezone was in the timezone arg which isn't how I'd understand "unless otherwise specified" to work.
> 
> How should the start/end/timezone args work?
> 
> DateUtils.parseUserPeriod and DateUtils.parseUserDuration are also creeping me out b/c the methods take a timezone and then do nothing with it.
> 
> When this issue is closed it would be great if the datetime parsing was solid, well tested and could be reused across all the controllers that need a ZonedDateTime and all the datetime parameter documentation matched what was being done.

I believe my original intention behind the code was to provide the timezone argument in cases where it's easier to provide than the full ISO format for start and end. If start and end contain TZ information, the timezone argument should be ignored. If start and end don't contain TZ information, then use the timezone argument, and assume start and end are in _that_ timezone.

That said, if timezone is supplied, and start and end contain TZ info, then I wouldn't be opposed to converting them to the specified timezone. It could be useful in cases where you want your output in a different timezone than your input.

**Comment by MikeNeilson** [comment]
Then again, the output is currently always in milliseconds from the unix epoch UTC.

**Comment by DanielTOsborne** [comment]
> Then again, the output is currently always in milliseconds from the unix epoch UTC.

Oh right, I forgot. 😆

**Comment by rma-rripken** [comment]
@DanielTOsborne thanks for weighing in.  I feel less crazy now.   I'm not ready to make the timezone arg into output timezone atm.  Its certainly something that could be done, it feels like a bigger change.   There is also the possibility of dropping the timezone argument and forcing users to be explicit.  I rather they were explicit than risk guessing wrong.   Another alternative would be to throw an error if start/end strings included timezone and timezone arg was also specified.  Or just an error if both specified and they don't match.   I'm ok with how things are atm but we can probably do even better.
